### ISSUE TITLE
Disable booting for Samsung S23 QCOM Series.

### ISSUE THREAD

**Issue by edgars-cirulis** [cawilliamson/treble_voltage#10]
Hello there. Can you disable Samsung S23 QCOM series booting? Would really Appreciate. 

WiWk, That changelog "Enable Galaxy S24 booting"  is nonsense.

**Comment by cawilliamson** [comment]
What? I don't understand what this means...

Why would you want a device to NOT boot anymore?

**Comment by cawilliamson** [comment]
Closing this one since it makes no sense. Please re-open if you can clarify what you actually want here.

**Comment by edgars-cirulis** [comment]
> Closing this one since it makes no sense. Please re-open if you can clarify what you actually want here.

"Enables Booting for S24" May you please describe the non-sense in which commit it enables?

**Comment by cawilliamson** [comment]
No. Next time show some respect.

**Comment by edgars-cirulis** [comment]
> No. Next time show some respect.

Then don't Write fake and nonsense changelog.

**Comment by cawilliamson** [comment]
https://github.com/cawilliamson/treble_voltage/blob/d14ab9232ca84644f45209e769978f3e55d88265/patches/trebledroid/platform_frameworks_base/0049-Also-override-UDFPS-infos-on-AIDL-fingerprints-neede.patch

https://github.com/TrebleDroid/treble_experimentations/releases/tag/ci-20240130

Your hostility is misplaced. We merge all TrebleDroid patches and they seem to have boot working properly on the S24. Therefore it should work on this ROM.

However your disgraceful behaviour has been reported to GitHub and I would appreciate you stop commenting on my work since you clearly have no experience in the field.

**Comment by edgars-cirulis** [comment]
Let me get you straight Into it, 
The patch in `AuthService.java`, it adds a static method `dynamicUdfpsProps(Context ctxt)` which retrieves dynamic UDFPS (Under Display Fingerprint Sensor) properties using the `DisplayManager`. It's made static and public so it can be accessed from other classes.
WiWi, 
In `FingerprintProvider.java`, it overrides UDFPS (Under Display Fingerprint Sensor) properties on AIDL (Android Interface Definition Language) fingerprints. It checks if the sensor location is at (0, 0) and if so, it replaces the location with dynamically retrieved UDFPS properties using the `AuthService.dynamicUdfpsProps(context)` method.

I do not see anything that's related to boot stuff.

**Comment by cawilliamson** [comment]
User blocked - problem solved.

Happy for people to submit bug reports but I donate a lot of my time to keep this maintained. I won't tolerate abuse.
