### ISSUE TITLE
Gms Compact Not working in 32-bits

### ISSUE THREAD

**Issue by Newbook2380** [cawilliamson/treble_voltage#18]
Hi chrisaw, how are you?, I came to tell you about the GMScompact not working in the 32 bit binder 64 version (although I'm not a fan of google), I only need gms for games, to see if you can put microg in the 32 bit version please.
![Screenshot_20240302-085509_Apps](https://github.com/cawilliamson/treble_voltage/assets/161945593/2f80a35a-b578-47ab-b3ce-6c961a9a4cda)

**Comment by cawilliamson** [comment]
Unfortunately there's nothing I can do on that - I added support for 32 bit devices to VoltageOS but the Sandboxed Gapps stuff comes directly from GrapheneOS and they don't support 32bit.

The best thing you can do is install MicroG via something like this: https://github.com/nift4/microg_installer_revived/releases

Sorry - I would add support for 32bit if it was possible but since that feature is entirely controlled by GrapheneOS and then it's just merged in to Voltage there's not much I can do to help! :(
