### ISSUE TITLE
Bug reports + suggestions & feature requests

### ISSUE THREAD

**Issue by erickmufath** [cawilliamson/treble_voltage#25]
Respectfully it's up to you, you shouldn't take my notes, but if you don't mind or this suits your preferences and if you can, it would be nice. Bug maybe only on my device-X678B, maybe not. Thank you.

- Some notification not appear in lock screen although i choose to Show All Notification in settings, like progress bar of copying large files in the background (spesifically i use FX File Manager).
- Lockscreen PIN with Face Unlock problem. Swipe to unlock with pin makes the number keys automatically zoom out and and zoom in(return to normal) based on the appearance of the text "Recognizing Face.."
- Cannot switch off SIM signal (This is different from airplane mode).
- Backup settings problem (seedvault missing).
- ★#★#4636#★#★ missing option to select prefered network frequency or band(not network type like GSM or LTE).
- Cannot switch on battery saver.
- If network permission turn off and turn on again(after boot/reboot) network on that app still not connected to the network until i reboot again.
- Grapheneos Camera problem, when switch from camera(photo) to video the result is like low light, and sometimes error appears.
- Signal icon become double (dual SIM have 4 icon) when swipe down to notification center in lanscape rotation/opening game, it's disappear and normal again only if expanding quick setting in notification center.
- Lag screen when refresh rate adaptive from higher refresh rate to 60hz, feels under 60fps(Youtube Shorts), but if i force to 60hz in phh treble settings, or in display settings set min and max refresh rate to 60hz or same value it feels normal(need reboot to take effect) (More detail : I found 60fps video on Shorts and it look like normal, it made me realize, that this issue occurs only when I touch the screen or anything else that affects changes on the screen except the video being played. Only when scrolling YouTube Shorts video or comments, including when animations or display movements increase or decrease the sound volume with buttons or touchscreen, definetely laggy and feels under 60fps)

- Increase the number of fingerprint inputs for one finger, the stock rom of my device is much more and it makes fingerprints more accurate.
- Add toggle front flashlight(if detected)
- Replace Jelly Browser with Vanadium.
- Replace AOSP Keyboard with FlorisBoard Keyboard(Other alternative : OpenBoard), AOSP Keyboard have problem like speech to text(mic icon) just a display(don't work) and cannot add or edit keyboard type in setting such a English (US), also it don't have integrated icon.

19/03/24
New bug reports and suggestions: 

I will not demand my report, please take notes if you can and don't mind according to your preferences.

- Beside Grapheneos camera problem before, just find out that my 108MP rear and 32MP selfie camera on DevCheck and AIDA64 not detected properly. Rear camera resolution detected just 12M with video resolution just 3.7MP, and selfie camera resolution detected 8.1MP with video resolution also 3.7MP, i think that is the main problem why the camera results are like that.
- Result of screen recording a bit blurry, with or without HEVC.
- Danmaku Notification Mode in Game Space dissapear too fast(maybe because it's danmaku or because while i playing game?! it feels too fast and sometimes i don't notice the notification). Can you make it more long or make it slowly slide from right to left to make it more noticable?.
- Gallery app useless for feature "Unlimited Backup Photos and Videos", makes me still should install other apps like original Google Photos app(maybe remove gallery and let user install whatever user want).
- Add charging control from LineagOS, like Voltage 2.8 GSI by ahnet-69
- Add toggle to show number of notification in dot notification app setting.

21/03/24
- In Airplane Mode with WIFI connected, when expanding quick acces or control center, 2 text "No Service" appear. And when phone locked, there are 2 empty signal icon with 2 same text "No Service". Normaly in Airplane Mode that should be not appear(or it should be "Airplane Mode" text?!).
- Monospace font show a bit weird. After installing termux, the font doesn't look good, some alphabet look wider than other. Not monospace font that i know.
- Add feature recent apps lock. So app don't close and keep running in the background, even if I press "Clear All" in recent apps, except click app logo in recent apps and unlock it.

22/3/24
Please take notes if this is useful as a reference for making the system better. If necessary, my report can also be forwarded to other developers.

- Split screen can only do 50-50 ratio. Other system that i know can do 75-25 or 25-75.
- GmsCompat keep show "Sandboxed Google Play is Running" even though i set GmsCompat, Google Service Framework, Google Play Service, and Google play to Restricted in "App battery usage" setting after boot/reboot. I don't know if this is normal and the setting just work like that, just reporting.
- Gaming not really smooth in graphic and network(ping) performance stability, maybe can you improve with someting like rendering mode and display compositing?!(Overall, not only on Game Space) Also improving touch response. I am not sure what i am talking about and can or cannot it can be. Also The game ping is too unstable, from 12 ms it can suddenly reach 8ms, 40ms(very unstable), sometimes can reach 200+ms and it can last a long time until the game character can't move. I know that the gaming experience depends on the chipset and network quality, but its graphic and network(ping) performance stability should not be slightly below average.

23/03/24
I will not demand that everything I have written be completed (If you take some notes). Whenever it is completed, it doesn't matter. For the sake of making the system better, I'll be happy to wait.

- Themed icon not applied on some apps. Can you sync themed icon to latest? In Pixel Experience 13(Official) with SIRIUS device before, apps i used mostly got themed icon, but in VoltageOS here, some of those apps icon don't change to themed icon although this is android 14.
- Battery drain and hot device. Beside battery saver issue before, can you apply mechanism to make device low power as device can, when idle, screen off, or there are just light task in the background? Also don't know why, just use the device with light task can make it hot and drain more battery. Luckily this problem can be solved with the KSU/Magisk module, but not as good as i expected. For 5000mAh battery this is still slightly below average.
- To make the audio better, can you implement surround sound on this system?! I am using original Type-C Apple Earpods, althought there is phhuson audio setting, i kinda feel no different. Just only one "Field Surround" enable in Viper4Android solved this and made sound more better, but again this requires the KSU/Magisk module.

25/3/24
- Optimize Grapheneos Network settings and add option disable to "Attestation key provisioning". Maybe can you optimize "Internet conectivity checks" and "Attestation key provisioning" and make it faster? When I don't have regular internet, shouldn't I not be able to access the internet on applications that have special internet access when "Internet connectivity checks" is active? My logic says it should work like that, but in fact it doesn't. I can still access it. Also just curious, every time I connect to WIFI(btw with 5GHz freq), it sometimes disconnect by itself and when connected again it doesn't immediately get an internet network, one time I even had to disconnect and reconnect WIFI manually. Could the issue occur because of these two things?!

27/3/24
- Notification Light(Not Notification Flash) not working and when i enable "use custom value" and click "Add Application" causes Settings force close.
- There are still some English text that are not translated into the language set by the system.

28/3/24
- Low download speed. It feels like its speed is limited, barely reaching the average speed when using the previous system to download large files. (Maybe related to previous network reports.)
- The charging voltage only stays at 5V, even though the device is capable of and supports fast charging of 11V or 21V(combined with Ampere support Max 68Watt). However, since this system has a Voltage indicator on the screen when charging, it seems that it is only stuck at 5V, which if you read the Charging Break, the Ampere output is only 2A or just 10W output.

30/3/24
- QR Code Scanner in quick setting/control center doesn't work and can't be clicked with "updating" text on it.
- Add configuration to the system microphone to make it better such as noise reduction and others. In the case of my device-X678B there are no problems, but when recording there is a slight 'ssss..' sound there(even when using Original Type-C Apple Earpods). If it is possible to set it on GSI, again if it suits your preferences, please consider it.

31/3/24
- Bluetooth icon doesn't appear in status bar when enabled.
- Add setting to enable/disable and control task animation speed like "Ultra Touch" feature in XOS (different from animation scale in developer options which reduces the animation scale, in personal opinion this accelerates the speed of the normal animation scale and/or swipe speed when doing something more than touch response. The effect will be felt on devices with a high refresh rate screen). Of course everything I said earlier applies and this is just an idea.

**Comment by Atman-5** [comment]
I'm sure some or most of the issues you described are related to vendor partition of your device and not the system GSI, you need a developer specifically for your device that would want to look into all that.

**Comment by erickmufath** [comment]
> I'm sure some or most of the issues you described are related to vendor partition of your device and not the system GSI, you need a developer specifically for your device that would want to look into all that.

Who knows?! Maybe it's from GSI, my partition vendor uses vendor stock and of course there are almost no problems if I use the stock system, is it possible that just changing the stock system to GSI can cause lots of bugs to appear? It would be better to inspect the GSI first. Logically it is possible that other users also experience the same thing and it can be fixed from there.

**Comment by Alien-Tec** [comment]
Hi there...

Here are some feature requests from me.

1. Remove AOSP Board and include Openboard + SayBoard (SpeechToText) + eSpeak (TextToSpeech).

2. Give the user the option to remove any preinstalled system app like file manager, gallery and so on - the same way iodéOS does it.
I love the SimpleMobileTools/Fossify - Set and would like to use these apps.

3. Keep on the good work. This GSI is awesome so far.

Regards.

**Comment by erickmufath** [comment]
> Hi there...
> 
> Here are some feature requests from me.
> 
> 1. Remove AOSP Board and include Openboard + SayBoard (SpeechToText) + eSpeak (TextToSpeech).
> 2. Give the user the option to remove any preinstalled system app like file manager, gallery and so on - the same way iodéOS does it.
>    I love the SimpleMobileTools/Fossify - Set and would like to use these apps.
> 3. Keep on the good work. This GSI is awesome so far.
> 
> Regards.

Maybe you should create a new issue despite the different requests. I have written about the request to replace the AOSP Keyboard but not SayBoard and about your request number 2.

**Comment by cawilliamson** [comment]
Wow, you have clearly taken a lot of time to provide all of this feedback so I'll try to go through it one by one:

**Some notification not appear in lock screen although i choose to Show All Notification in settings, like progress bar of copying large files in the background (spesifically i use FX File Manager).**

Device or ROM issue - not GSI specific.

**Lockscreen PIN with Face Unlock problem. Swipe to unlock with pin makes the number keys automatically zoom out and and zoom in(return to normal) based on the appearance of the text "Recognizing Face.."**

Device or ROM issue - not GSI specific.

**Cannot switch off SIM signal (This is different from airplane mode).**

Device or ROM issue - not GSI specific.

**Backup settings problem (seedvault missing).**

Can you provide clarification on this? I was fairly certain Seedvault was present!



**★#★#4636#★#★ missing option to select prefered network frequency or band(not network type like GSM or LTE).**

Device or ROM issue - not GSI specific.

**Cannot switch on battery saver.**

Can you provide additional information here?

**If network permission turn off and turn on again(after boot/reboot) network on that app still not connected to the network until i reboot again.**

That is strange but is very likely a ROM issue since there is nothing GSI specific here. May be worth raising this with the VoltageOS developers.

**Grapheneos Camera problem, when switch from camera(photo) to video the result is like low light, and sometimes error appears.**

I have removed GrapheneOS camera and reverted back to the LineageOS Aperture camera app in the new builds (coming soon - just working out the bugs!)

**Signal icon become double (dual SIM have 4 icon) when swipe down to notification center in lanscape rotation/opening game, it's disappear and normal again only if expanding quick setting in notification center.**

Device or ROM issue - not GSI specific.

**Lag screen when refresh rate adaptive from higher refresh rate to 60hz, feels under 60fps(Youtube Shorts), but if i force to 60hz in phh treble settings, or in display settings set min and max refresh rate to 60hz or same value it feels normal(need reboot to take effect) (More detail : I found 60fps video on Shorts and it look like normal, it made me realize, that this issue occurs only when I touch the screen or anything else that affects changes on the screen except the video being played. Only when scrolling YouTube Shorts video or comments, including when animations or display movements increase or decrease the sound volume with buttons or touchscreen, definetely laggy and feels under 60fps)**

Device or ROM issue - not GSI specific.

**Increase the number of fingerprint inputs for one finger, the stock rom of my device is much more and it makes fingerprints more accurate.**

ROM request - should be directed to VoltageOS development team.

**Add toggle front flashlight(if detected)**

ROM request - should be directed to VoltageOS development team.

**Replace Jelly Browser with Vanadium.**

I will consider this - Jelly Browser is, indeed, not my favourite by far!

**Replace AOSP Keyboard with FlorisBoard Keyboard(Other alternative : OpenBoard), AOSP Keyboard have problem like speech to text(mic icon) just a display(don't work) and cannot add or edit keyboard type in setting such a English (US), also it don't have integrated icon.**

**Beside Grapheneos camera problem before, just find out that my 108MP rear and 32MP selfie camera on DevCheck and AIDA64 not detected properly. Rear camera resolution detected just 12M with video resolution just 3.7MP, and selfie camera resolution detected 8.1MP with video resolution also 3.7MP, i think that is the main problem why the camera results are like that.**

Device or ROM issue - not GSI specific.

May be resolved by switch back to Aperture in coming builds.

**Result of screen recording a bit blurry, with or without HEVC.**

Device or ROM issue - not GSI specific.

**Danmaku Notification Mode in Game Space dissapear too fast(maybe because it's danmaku or because while i playing game?! it feels too fast and sometimes i don't notice the notification). Can you make it more long or make it slowly slide from right to left to make it more noticable?**

ROM request - should be directed to VoltageOS development team.

**Gallery app useless for feature "Unlimited Backup Photos and Videos", makes me still should install other apps like original Google Photos app(maybe remove gallery and let user install whatever user want).**

Not useless at all - if you want to use Google Photos then install it and disable Gallery as you wish. The option is yours.

**Add charging control from LineagOS, like Voltage 2.8 GSI by ahnet-69**

ROM request - should be directed to VoltageOS development team.

**Add toggle to show number of notification in dot notification app setting.**

ROM request - should be directed to VoltageOS development team.

**In Airplane Mode with WIFI connected, when expanding quick acces or control center, 2 text "No Service" appear. And when phone locked, there are 2 empty signal icon with 2 same text "No Service". Normaly in Airplane Mode that should be not appear(or it should be "Airplane Mode" text?!).**

ROM request - should be directed to VoltageOS development team.

**Monospace font show a bit weird. After installing termux, the font doesn't look good, some alphabet look wider than other. Not monospace font that i know.**

ROM request - should be directed to VoltageOS development team.

**Add feature recent apps lock. So app don't close and keep running in the background, even if I press "Clear All" in recent apps, except click app logo in recent apps and unlock it.**

This will be resolved by switching back to VoltageOS launcher - included by default in coming builds.

**Split screen can only do 50-50 ratio. Other system that i know can do 75-25 or 25-75.**

ROM request - should be directed to VoltageOS development team.

**GmsCompat keep show "Sandboxed Google Play is Running" even though i set GmsCompat, Google Service Framework, Google Play Service, and Google play to Restricted in "App battery usage" setting after boot/reboot. I don't know if this is normal and the setting just work like that, just reporting.**

This is normal - just disable the background service notification and it'll go away. :)

**Gaming not really smooth in graphic and network(ping) performance stability, maybe can you improve with someting like rendering mode and display compositing?!(Overall, not only on Game Space) Also improving touch response. I am not sure what i am talking about and can or cannot it can be. Also The game ping is too unstable, from 12 ms it can suddenly reach 8ms, 40ms(very unstable), sometimes can reach 200+ms and it can last a long time until the game character can't move. I know that the gaming experience depends on the chipset and network quality, but its graphic and network(ping) performance stability should not be slightly below average.**

Device or ROM issue - not GSI specific.

**Themed icon not applied on some apps. Can you sync themed icon to latest? In Pixel Experience 13(Official) with SIRIUS device before, apps i used mostly got themed icon, but in VoltageOS here, some of those apps icon don't change to themed icon although this is android 14.**

ROM request - should be directed to VoltageOS development team.

**Battery drain and hot device. Beside battery saver issue before, can you apply mechanism to make device low power as device can, when idle, screen off, or there are just light task in the background? Also don't know why, just use the device with light task can make it hot and drain more battery. Luckily this problem can be solved with the KSU/Magisk module, but not as good as i expected. For 5000mAh battery this is still slightly below average.**

ROM request - should be directed to VoltageOS development team.

**To make the audio better, can you implement surround sound on this system?! I am using original Type-C Apple Earpods, althought there is phhuson audio setting, i kinda feel no different. Just only one "Field Surround" enable in Viper4Android solved this and made sound more better, but again this requires the KSU/Magisk module.**

ROM request - should be directed to VoltageOS development team.

**Optimize Grapheneos Network settings and add option disable to "Attestation key provisioning". Maybe can you optimize "Internet conectivity checks" and "Attestation key provisioning" and make it faster? When I don't have regular internet, shouldn't I not be able to access the internet on applications that have special internet access when "Internet connectivity checks" is active? My logic says it should work like that, but in fact it doesn't. I can still access it. Also just curious, every time I connect to WIFI(btw with 5GHz freq), it sometimes disconnect by itself and when connected again it doesn't immediately get an internet network, one time I even had to disconnect and reconnect WIFI manually. Could the issue occur because of these two things?!**

Device or ROM issue - not GSI specific.

**Notification Light(Not Notification Flash) not working and when i enable "use custom value" and click "Add Application" causes Settings force close.**

Device or ROM issue - not GSI specific.

**There are still some English text that are not translated into the language set by the system.**

This should be reported to the VoltageOS development team.

**Low download speed. It feels like its speed is limited, barely reaching the average speed when using the previous system to download large files. (Maybe related to previous network reports.)**

Device or ROM issue - not GSI specific.

**The charging voltage only stays at 5V, even though the device is capable of and supports fast charging of 11V or 21V(combined with Ampere support Max 68Watt). However, since this system has a Voltage indicator on the screen when charging, it seems that it is only stuck at 5V, which if you read the Charging Break, the Ampere output is only 2A or just 10W output.**

Device or ROM issue - not GSI specific.

**QR Code Scanner in quick setting/control center doesn't work and can't be clicked with "updating" text on it.**

Device or ROM issue - not GSI specific.

**Add configuration to the system microphone to make it better such as noise reduction and others. In the case of my device-X678B there are no problems, but when recording there is a slight 'ssss..' sound there(even when using Original Type-C Apple Earpods). If it is possible to set it on GSI, again if it suits your preferences, please consider it.**

Device or ROM issue - not GSI specific.

**Bluetooth icon doesn't appear in status bar when enabled.**

Device or ROM issue - not GSI specific.

**Add setting to enable/disable and control task animation speed like "Ultra Touch" feature in XOS (different from animation scale in developer options which reduces the animation scale, in personal opinion this accelerates the speed of the normal animation scale and/or swipe speed when doing something more than touch response. The effect will be felt on devices with a high refresh rate screen). Of course everything I said earlier applies and this is just an idea.**

ROM request - should be directed to VoltageOS development team.




**Summary:**

A lot of what you're asking for is either:

1. Feature requests - for the most part these belong with the VoltageOS team - I don't build the ROM - I just adapt it for GSIs.
2. Device issues - these are not the device itself but how it's interacting with GSIs in general. For general device => GSI issues you would want to raise them with https://github.com/TrebleDroid/treble_experimentations/issues - they will be much more equipped to assist you but be aware - that's NOT for Voltage specific stuff - just general "stuff doesn't work right on my device on GSI based ROMs" stuff.

**Comment by erickmufath** [comment]
Thank you for the reply and answer. I found all of that because I really use it for my daily needs. In general, I understand. Also   regarding several reports or requests that must be submitted directly to the VoltageOS team. But as long as they don't develop GSI, I'm not sure how to submit my report to them, especially if I can't try their official ROM due to device support issues. Do you have any suggestions regarding this? or maybe you can forward it to them based on the points that you think are worthy? 

Some more information requested + new report : 
- Seedvault missing. When I go to the backup section in system settings, when I activate backup nothing happens, after it is activated a recovery code display in the form of 12 words should appear. In 1 or 2 versions before the latest, when activated there would be an error until it forced close (if I remember correctly), then there was another seedvault error notification in the notification center which if clicked would go straight to the 12 word recovery code or the start of the seedvault backup process, but in the latest version nothing happens at all. 
- Cannot enable battery saver. In the control center it cannot be activated at all, you can click it but nothing happens, even though a low battery notification appears and ask to activate, from there it also doesn't change anything.

10/4/24 {
Sometimes besides major bugs, minor bugs also often occur(sometimes/not always. Because this bug is minor, it's not too annoying and it only happens sometimes which makes fixing it more difficult, ignoring it is fine, but if it can be found and fixed it would be very good), for example : 
- The digital clock numbers on the lock screen don't appear if you accidentally press the power button : twice or after doing task quickly.
- The status bar disappears and you can't swipe down when opening app, example : YouTube (like being locked in full screen mode).
- One touch become double touch.

I just wish the GSI was optimized more. Do you could make the storage size used for the system smaller? 15GB and above is too big, it would be perfect if it was like the Pixel 8 Pro which only uses 3.6GB of system storage when you see the review on YouTube. I found that the Pixel 8 Pro is a 64-bit only device, I don't know if this also affects the size of the system storage used, but at least under 10GB like the size of the HyperOS system in one of the Xiaomi review videos I watched is quite okay. Just wanted to express my opinion. I know that you just adapted the ROM to GSI but I don't know how much control you have over this GSI and what you can do with it.
}
27/4/24 {
- Cannot charge in turnoff mode, only lightning logo appear which never change into percentage. To test i left it for a while, and turned the device back on, but the battery percentage did'nt increase.
}

Also, are you really unable to adjust the rendering mode or anything regarding the  graphics? something like skiagl or vulkan. I've seen it while browsing GitHub which seems to contain several graphic settings and others with the name system.prop

Edit : I've been using Indonesian all this time and I just discovered something new, when I changed it to English to take a screenshot as evidence, the backup section of the system changed. It looks like the seedvault report and some others may be related to this. Previously I did not attach screenshot evidence because it would be too much, and some cannot only be proven with screenshot evidence but video evidence.
![Screenshot_20240404-063446_Setelan](https://github.com/cawilliamson/treble_voltage/assets/90117993/98fc5f4f-f9e7-4bae-bdee-166f1aecb31b)
![Screenshot_20240404-063459_Settings](https://github.com/cawilliamson/treble_voltage/assets/90117993/43cdb52a-fbb8-4cb7-95ab-e0ac81182974)

**Comment by erickmufath** [comment]
![Screenshot_20240404-063446_Setelan](https://github.com/cawilliamson/treble_voltage/assets/90117993/8224d6e5-5be2-4395-be51-871975a52fd3)
![Screenshot_20240404-063459_Settings](https://github.com/cawilliamson/treble_voltage/assets/90117993/2ca9ca4f-5a9e-4bae-8307-0644c88356da)

**Comment by cawilliamson** [comment]
Pretty much everything you're describing there are issues with either device specific patches or Voltage itself - I'm just adapting Voltage to run as a GSI - I can't adapt / fix / patch every single problem with it unfortunately. I just don't have the resources and it would essentially be a different ROM at that point.

For device specific stuff I suggest raising a ticket at https://github.com/TrebleDroid/treble_experimentations/issues although I would try to keep your ticket more short and to the point or it'll likely be ignored there. :)

For Voltage stuff... don't really know what to suggest. I found them to be incredibly hostile when I suggested a change so I don't communicate with them at all.
