### ISSUE TITLE
[bug？]The screen goes black except for a part of it.

### ISSUE THREAD

**Issue by ghost** [cawilliamson/treble_voltage#43]
Symptoms: The screen goes black except for a part of it.
![Screenshot_20240824-121743](https://github.com/user-attachments/assets/d8228d32-f55e-4a88-bdd7-0c15f1e77508)
https://github.com/user-attachments/assets/156340c6-14b9-4744-9a9c-b35dfc64a908

〈When does this happen?〉
It happens irregularly.
But it happens in two ways:
・When switching from an app to the home screen
・When opening an app from the home screen

〈Solution〉
Press the “task management button” several times. (The ■ button.)

Usage environment
・Xperia 5 IV
・Rooted
・VoltageOS-vanilla-arm64-ab-3.5-20240731-UNOFFICIAL.img.xz

**Comment by cawilliamson** [comment]
I've just pushed a new build - very few TD changes but there are some VoltageOS changes - hopefully that helped! :+1: 

If not - this will likely need to be raised with the fine folks over at https://github.com/TrebleDroid/treble_experimentations/issues since it sounds like a TrebleDroid patches issue instead of a ROM issue.

There's nothing very GSI specific in the ROM which would cause this.

**Comment by ghost** [comment]
I also encountered a bug with VoltageOS-vanilla-arm64-ab-3.6-20240827-UNOFFICIAL.img.xz that caused some screens to turn black, so I reported this to https://github.com/TrebleDroid/treble_experimentations/issues.
